# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e674b8171b0f510691f170a3f434286d0f5e8c690728268c54c19261ad79fe81cccd629be5aab5438ac525ed6dc9f897538089adfa2a45476f19861ca044a55

test:
  secret_key_base: 370aa1bd7dda9f112172fe4f165fdadf39176cb7885a4e74b6065f7649c6ebe12b642d1850afd2b8c1f5cbbfadcd829657d1d8674127380cca5a21da1de2bcde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
